# Generated by Django 3.2.8 on 2021-10-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='picture',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
