# Generated by Django 3.2.8 on 2021-10-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPC', '0002_auto_20211011_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='image',
            field=models.ImageField(upload_to='home/habeeb/Documents/Strategypandc/media/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='picture',
            field=models.ImageField(upload_to='home/habeeb/Documents/Strategypandc/media/'),
        ),
    ]
