# Generated by Django 3.2.8 on 2021-10-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPC', '0004_auto_20211011_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='image',
            field=models.ImageField(upload_to='insight/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='picture',
            field=models.ImageField(upload_to='team/'),
        ),
    ]
