# Generated by Django 3.2.8 on 2021-10-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPC', '0005_auto_20211011_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
