# Generated by Django 2.2.24 on 2021-10-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPC', '0006_alter_insight_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insight',
            name='intro',
        ),
        migrations.AlterField(
            model_name='insight',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
