# Generated by Django 3.2.8 on 2021-10-19 14:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SPC', '0009_alter_insight_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
