# Generated by Django 3.2.8 on 2021-10-19 14:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SPC', '0010_alter_team_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='body',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
