# Generated by Django 3.2.8 on 2021-10-19 15:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SPC', '0011_alter_insight_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
